#mysql properties
[mysql]
url=localhost
driver=com.mysql.cj.jdbc.Driver
username=quizadmin
password=Simple12*#
database=stocksdb
table=stocksinfp
earning_table=stocks_earnings
revenue_table=quarterly_financials
stock_change_tracker_table=stock_change_tracker
[stocks]
#symbols=AAPL ABBV ACB AFRM AI ALB ALEC ALGM ALGT ALT AMBA AMC AMD AMEH AMTX AMZN ANVS AON APP APPN APPS ARVN ASXC ATOM ATOS AVXL BB BBBY BBW BDL BEAM BFLY BGNE BLFS BLIN BNTX BPTH BTBT BTU BYSI CARV  CELH CFLT CGC CHS CLNE CLOV CMP COIN COO COUR CRM CRNC CROX CRSR CRWD CVRX CXM CXW CYRX DASH DDD DE DIS DKS DOCS DQ DVAX DXCM EBET EDIT ELP ESEA ESGR EVBG EXPE FIGS FIVE FLYW FSLY FTNT FUV GME GOOG HCA HMHC HOL HOOD IDT IGT INMD IT ITOS JKS JMIA JYNT KNBE KOSS LAD LAW LB LEDS LFST LI LLY MANH MARA ME META MNDY MOXC MRIN MRNA MRO MSFT MTP MTSI MUDS MVIS NEGG NET NFLX NIO NKE NLST NOC NTLA NTR NUE NURO NVAX NVDA NVRO NVS OCGN OKTA OMI OMIC ORCL ORMP OSAT PANW PAVM PAY PAYC PDCE PETS PFE PINS PLBY PLTR PRTA PTGX PVH PXLW PYPL QDEL QFIN QS QTT RAPT RAVN RBLX RDFN REAL REGI RHE RIOT ROKU ROOT SANA SAP SAVA SB SE SEDG SENS SGHT SI SKLZ SKY SNAP SNDL SNOW SOXL SPCE SPRT SPT SQBG SRNE STFC SYY TASK TATT TEN TFII TPST TRIL TRIP TSEM TSLA TTD TTI TTM U UI UONE UPST URI USCR USEG VEEV VER VIEW VNE VRTV W WDAY WISH YOU ZIXI ZS RGTI QTUM WGS KINS ACHR STM EXFY QUBT SMCI QCOM POET SOUN IOT RR CLS RXRX PCOR KC NBIS OPFI POWL WRD ADI BMRN CRL GRMN
symbols=

[spark]
mysql_jar_path = /Users/gaurav/.m2/repository/com/mysql/mysql-connector-j/8.0.33/mysql-connector-j-8.0.33.jar

[threading]
max_workers = 2
timeout_seconds = 30